# 认证配置
auth:
  host:
    # deploy to server need config to "*"
    cors: http://localhost:8080,http://127.0.0.1:8080
  filter:
    excludes: /api/auth/*,/websocket/**,/api/server/word/*
  api:
    excludes: /websocket/**,/api/server/word/*
    loginApi: /api/auth/login
    freeApi: /api/auth/*
    userApi: /api/business/**
    adminApi: /api/business/**
