server:
  port: 9090
  servlet:
    context-path: /dailyWord


spring:
  # 邮件配置, For register send mail
  mail:
    host: smtp.163.com
    port: 465
    username: 123456@163.com
    password: 123456
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
