server:
  port: 9090
  servlet:
    context-path: /dailyWord

# 认证配置
auth:
  host:
    cors: http://localhost:8080,http://127.0.0.1:8080
  api:
    login: /api/auth/login
    free: /api/auth/login,/api/auth/register,/api/auth/forgot
    user: /api/word/**
    admin: /api/word/**

# 绑定 MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.ibudai.entity
  # 控制台打印 sql 语句
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
